---

    name: Checklist
    
    on:
      pull_request_target:
        types:
          - opened
          - synchronize
          - reopened
        paths:
          - applications/**/*.json
    
    jobs:
      setup:
        name: Setup
        runs-on: ubuntu-latest
    
        steps:
          - name: Checklist
            uses: elementary/action-appcenter-review-checklist@v1.0.2
            with:
              token: ${{ secrets.GIT_USER_TOKEN }}
              body: |
                ## Review Checklist
    
                - [ ] App opens
                - [ ] Does what it says
                - [ ] Categories match
                
                ### AppData
                - [ ] Name is unique and non-confusing
                - [ ] Matches description
                - [ ] Matches screenshot
                - [ ] Launchable tag with matching ID
                - [ ] Release tag with matching version and YYYY-MM-DD date
                - [ ] Custom colors meet WCAG A contrast or greater
                - [ ] OARS info matches
                
                ### Flatpak
                - [ ] Uses elementary runtime
                - [ ] Sandbox permissions are reasonable
    
      